// lib/phoneData.ts
import { Phone } from "@/types/phone";

export const phonesData: Phone[] = [
  {
    slug: "apple-iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    brand: "Apple",
    brandLogo: "Apple",
    year: 2026,
    rating: 4.9,
    reviewCount: 1245,
    isFlagship: true,
    isEditorChoice: true,
    tags: ["Titanium", "5G", "IP68", "A18 Pro", "AI"],
    image: "/images/s24ultra.jpg",
    specs: {
      display: "6.9 inches",
      displayType: "Super Retina XDR (OLED)",
      resolution: "2868 × 1320 px",
      pixelDensity: "460 ppi",
      screenToBodyRatio: "~87.2%",
      refreshRate: "120Hz ProMotion",
      brightness: "1000 nits typ · 2500 nits peak",
      protection: "Ceramic Shield 2.0",
      hdrSupport: "HDR10, Dolby Vision",
      alwaysOnDisplay: "✅ Yes",
      chipset: "A18 Pro",
      cpu: "Hexa-core (2×4.05GHz Everest + 4×2.42GHz Sawtooth)",
      gpu: "Apple GPU 6-core, ray tracing hardware",
      neuralEngine: "16-core Neural Engine, 38 TOPS",
      ram: "12 GB",
      ramType: "LPDDR5X",
      storage: "256 GB / 512 GB / 1 TB / 2 TB",
      storageType: "NVMe",
      camera: "48 MP",
      cameraWide: "48 MP, f/1.78, 24mm, 1/1.28\", 1.22µm, OIS",
      cameraUltraWide: "48 MP, f/2.2, 13mm, 120°",
      cameraTelephoto: "12 MP, f/2.8, 120mm, 5× optical zoom, OIS",
      cameraFeatures: "LED flash, Photonic Engine, Deep Fusion, Smart HDR 6, Night mode, Portrait mode, ProRAW, 48MP HEIF",
      videoRecording: "8K@24/30fps, 4K@24/25/30/60/120fps, ProRes, Dolby Vision HDR, 10-bit HDR, Log video",
      frontCamera: "12 MP, f/1.9, 23mm, 1/3.6\", autofocus, OIS",
      frontFeatures: "Photonic Engine, Deep Fusion, Smart HDR 6, Night mode, Portrait mode, 4K HDR video",
      dimensions: "160.9 × 77.8 × 8.3 mm",
      weight: "225 g",
      build: "Grade 5 Titanium frame · Ceramic Shield 2.0 front · textured matte glass back",
      colors: ["Black Titanium", "White Titanium", "Natural Titanium", "Desert Titanium"],
      colorFinish: "PVD coating on titanium frame",
      waterResistance: "IP68 (6m, 30 min)",
      battery: "4685 mAh",
      batteryType: "Li-Ion, non-removable",
      wiredCharging: "45W fast charge, 50% in ~20 min",
      wirelessCharging: "MagSafe 25W · Qi 15W",
      batteryTechnology: "Adaptive charging, optimized battery charging",
      videoPlayback: "Up to 33 hours",
      audioPlayback: "Up to 105 hours",
      standbyTime: "~600 hours",
      os: "iOS 18, upgradable to iOS 19",
      osUpdates: "6+ years of OS updates",
      audio: "Stereo speakers, Dolby Atmos, Spatial Audio",
      headphoneJack: "No (USB-C)",
      audioRecording: "Stereo recording, Studio-quality mics",
      sim: "Nano-SIM + eSIM / Dual eSIM",
      networkBands: "5G NR (n1, n2, n3, n5, n7, n8, n12, n20, n25, n28, n30, n38, n40, n41, n48, n66, n70, n71, n77, n78, n79), 4G LTE, 3G, 2G",
      wifi: "Wi-Fi 7 (802.11be) with 2×2 MIMO",
      bluetooth: "5.4, A2DP, LE, aptX HD, aptX Lossless",
      nfc: "Yes (NFC, Apple Pay)",
      usb: "USB-C 3.2 (up to 20Gbps)",
      gps: "GPS, GLONASS, GALILEO, BDS, QZSS, NavIC",
      ultraWideband: "UWB chip for spatial awareness",
      satelliteSOS: "Emergency SOS via satellite",
      crashDetection: "Yes",
      threadSupport: "Yes (Thread networking)",
      security: "Face ID, Secure Enclave, AI-powered security",
      sensors: "Face ID, LiDAR scanner, accelerometer, gyro, proximity, barometer, compass, ambient light sensor, ECG",
      applePay: "✅ Yes",
      magSafe: "Yes, with 25W charging",
      emergencySOS: "✅ Yes",
      boxContents: "iPhone 16 Pro Max, USB-C charge cable (1m), Documentation",
      models: ["A3085 (US)", "A3104 (Intl)"],
      pricing: ["$1199 · 256GB", "$1399 · 512GB", "$1599 · 1TB", "$1799 · 2TB"],
    },
    benchmarks: {
      antutu: 2200000,
      geekbench6Single: 3800,
      geekbench6Multi: 9500,
      wildLifeExtreme: "~5200",
    },
    stats: {
      views: "45.2K",
      favorites: "12.8K",
      shares: "3.4K",
      reviews: "1245",
    },
  },
  {
    slug: "samsung-galaxy-s25-ultra",
    name: "Galaxy S25 Ultra",
    brand: "Samsung",
    brandLogo: "Samsung",
    year: 2026,
    rating: 4.8,
    reviewCount: 987,
    isFlagship: true,
    isEditorChoice: true,
    tags: ["Titanium", "5G", "IP68", "S Pen", "200MP", "AI"],
    image: "/images/s24ultra.jpg",
    specs: {
      display: "6.9 inches",
      displayType: "Dynamic AMOLED 3X",
      resolution: "3200 × 1440 px",
      pixelDensity: "515 ppi",
      screenToBodyRatio: "~89.3%",
      refreshRate: "144Hz Adaptive",
      brightness: "3000 nits peak",
      protection: "Gorilla Glass Armor 2",
      hdrSupport: "HDR10+, HDR10",
      alwaysOnDisplay: "✅ Yes",
      chipset: "Snapdragon 8 Gen 4 for Galaxy",
      cpu: "Octa-core (1×4.32GHz Cortex-X5 + 5×3.5GHz Cortex-A730 + 2×2.5GHz Cortex-A530)",
      gpu: "Adreno 830",
      neuralEngine: "Hexagon NPU, 45 TOPS",
      ram: "16 GB",
      ramType: "LPDDR5X",
      storage: "256 GB / 512 GB / 1 TB / 2 TB",
      storageType: "UFS 4.1",
      camera: "200 MP",
      cameraWide: "200 MP, f/1.6, 23mm, 1/1.3\", 0.7µm, OIS",
      cameraUltraWide: "50 MP, f/2.0, 14mm, 120°",
      cameraTelephoto: "50 MP, f/3.4, 115mm, 5× optical zoom, OIS",
      cameraFeatures: "LED flash, 8K video recording, Nightography 2.0, Portrait mode, Pro mode, Expert RAW, AI Photography",
      videoRecording: "8K@30/60fps, 4K@30/60/120fps, 1080p@30/60/240fps, HDR10+, Dolby Vision",
      frontCamera: "12 MP, f/2.0, 26mm, 1/3.2\", PDAF, Dual Pixel",
      frontFeatures: "Dual Pixel PDAF, 4K video, HDR, Portrait mode, AI Beautification",
      dimensions: "162.8 × 79.4 × 8.4 mm",
      weight: "228 g",
      build: "Titanium frame · Gorilla Glass Armor 2 front/back",
      colors: ["Titanium Black", "Titanium Gray", "Titanium Violet", "Titanium Gold", "Titanium Blue"],
      colorFinish: "Titanium frame with matte finish",
      waterResistance: "IP68 (1.5m, 30 min)",
      battery: "5500 mAh",
      batteryType: "Li-Ion, non-removable",
      wiredCharging: "65W fast charge, 70% in 30 min",
      wirelessCharging: "25W Qi/PMA, 15W reverse wireless",
      batteryTechnology: "Adaptive charging, battery health monitoring, AI power management",
      videoPlayback: "Up to 36 hours",
      audioPlayback: "Up to 120 hours",
      standbyTime: "~650 hours",
      os: "Android 15, upgradable to Android 16",
      osUpdates: "7 years of OS updates",
      audio: "Stereo speakers, Dolby Atmos, AKG tuning, 32-bit/384kHz",
      headphoneJack: "No (USB-C)",
      audioRecording: "Stereo recording, 360 Audio, noise cancellation",
      sim: "Nano-SIM + eSIM / Dual SIM",
      networkBands: "5G NR (n1, n2, n3, n5, n7, n8, n12, n20, n25, n28, n38, n40, n41, n66, n71, n77, n78, n79), 4G LTE, 3G, 2G",
      wifi: "Wi-Fi 7 (802.11be) with 2×2 MIMO",
      bluetooth: "5.4, A2DP, LE, aptX HD, LDAC, aptX Lossless",
      nfc: "Yes (NFC, Samsung Pay)",
      usb: "USB-C 3.2 (up to 20Gbps)",
      gps: "GPS, GLONASS, GALILEO, BDS, QZSS, NavIC",
      ultraWideband: "UWB chip for spatial awareness",
      satelliteSOS: "Emergency SOS via satellite",
      crashDetection: "Yes",
      threadSupport: "Yes (Thread networking)",
      security: "Ultrasonic fingerprint, Samsung Knox, Secure Folder, Biometric authentication",
      sensors: "Ultrasonic fingerprint, accelerometer, gyro, proximity, barometer, compass, ambient light sensor, hall sensor, SPO2",
      applePay: "No",
      magSafe: "No",
      emergencySOS: "Yes",
      boxContents: "Galaxy S25 Ultra, USB-C cable, SIM tool, Documentation, S Pen",
      models: ["SM-S938B (Global)", "SM-S938U (US)", "SM-S938W (Canada)"],
      pricing: ["$1299 · 256GB", "$1499 · 512GB", "$1699 · 1TB", "$1899 · 2TB"],
    },
    benchmarks: {
      antutu: 2450000,
      geekbench6Single: 3200,
      geekbench6Multi: 9800,
      wildLifeExtreme: "~5500",
    },
    stats: {
      views: "38.7K",
      favorites: "9.2K",
      shares: "2.8K",
      reviews: "987",
    },
  },
  {
    slug: "google-pixel-9-pro-xl",
    name: "Pixel 9 Pro XL",
    brand: "Google",
    brandLogo: "Google",
    year: 2026,
    rating: 4.7,
    reviewCount: 876,
    isFlagship: true,
    isEditorChoice: true,
    tags: ["5G", "AI", "Camera", "Stock Android", "Tensor G4"],
    image: "/images/s24ultra.jpg",
    specs: {
      display: "6.8 inches",
      displayType: "LTPO OLED",
      resolution: "2992 × 1344 px",
      pixelDensity: "489 ppi",
      screenToBodyRatio: "~87.8%",
      refreshRate: "144Hz Adaptive",
      brightness: "2600 nits peak",
      protection: "Gorilla Glass Victus 3",
      hdrSupport: "HDR10+, Dolby Vision",
      alwaysOnDisplay: "✅ Yes",
      chipset: "Google Tensor G4",
      cpu: "Nona-core (1×3.2GHz Cortex-X4 + 4×2.6GHz Cortex-A720 + 4×2.2GHz Cortex-A520)",
      gpu: "Immortalis-G720 MC12",
      neuralEngine: "TPU 4.0 for AI processing, Titan M3 security, 50 TOPS",
      ram: "16 GB",
      ramType: "LPDDR5X",
      storage: "128 GB / 256 GB / 512 GB / 1 TB",
      storageType: "UFS 4.0",
      camera: "50 MP",
      cameraWide: "50 MP, f/1.68, 25mm, 1/1.31\", 1.2µm, OIS",
      cameraUltraWide: "50 MP, f/1.95, 13mm, 125.5°",
      cameraTelephoto: "50 MP, f/2.8, 120mm, 5× optical zoom, OIS",
      cameraFeatures: "LED flash, Super Res Zoom, Magic Eraser, Photo Unblur, Night Sight, Real Tone, Macro Focus, AI Photography",
      videoRecording: "8K@30fps, 4K@30/60/120fps, 1080p@30/60/120/240fps, 10-bit HDR, Cinematic Pan",
      frontCamera: "12 MP, f/2.0, 20mm, 1/3.1\", PDAF",
      frontFeatures: "4K video, HDR, Portrait mode, Face Unlock, AI Beauty",
      dimensions: "162.6 × 76.5 × 8.5 mm",
      weight: "218 g",
      build: "Titanium frame · Gorilla Glass Victus 3 front/back",
      colors: ["Obsidian", "Porcelain", "Bay", "Rose"],
      colorFinish: "Satin titanium frame, matte glass back",
      waterResistance: "IP68 (1.5m, 30 min)",
      battery: "5400 mAh",
      batteryType: "Li-Ion, non-removable",
      wiredCharging: "45W fast charge, 50% in 25 min",
      wirelessCharging: "30W Qi, 15W reverse wireless",
      batteryTechnology: "Adaptive charging, battery health monitoring, AI power management",
      videoPlayback: "Up to 30 hours",
      audioPlayback: "Up to 95 hours",
      standbyTime: "~550 hours",
      os: "Android 15, upgradable to Android 16",
      osUpdates: "7 years of OS updates, Feature Drops",
      audio: "Stereo speakers, Spatial Audio, noise cancellation, AI audio enhancement",
      headphoneJack: "No (USB-C)",
      audioRecording: "Stereo recording, Audio Magic Eraser, Zoom Enhance, AI audio",
      sim: "Nano-SIM + eSIM",
      networkBands: "5G NR (n1, n2, n3, n5, n7, n8, n12, n20, n25, n28, n38, n40, n41, n66, n71, n77, n78, n79), 4G LTE, 3G, 2G",
      wifi: "Wi-Fi 7 (802.11be) with 2×2 MIMO",
      bluetooth: "5.4, A2DP, LE, aptX HD, LDAC, aptX Lossless",
      nfc: "Yes (NFC, Google Pay)",
      usb: "USB-C 3.2 (up to 20Gbps)",
      gps: "GPS, GLONASS, GALILEO, BDS, QZSS, NavIC",
      ultraWideband: "UWB chip for spatial awareness",
      satelliteSOS: "Emergency SOS via satellite",
      crashDetection: "Yes",
      threadSupport: "Yes (Thread networking)",
      security: "Face Unlock, Fingerprint, Titan M3 chip, VPN by Google, AI Security",
      sensors: "Face unlock, fingerprint, accelerometer, gyro, proximity, barometer, compass, ambient light sensor, thermometer, magnetometer, SPO2",
      applePay: "No",
      magSafe: "No",
      emergencySOS: "Yes",
      boxContents: "Pixel 9 Pro XL, USB-C cable, Quick Switch Adapter, Documentation",
      models: ["G1MNW (Global)", "G9BQD (US)"],
      pricing: ["$1099 · 128GB", "$1199 · 256GB", "$1399 · 512GB", "$1599 · 1TB"],
    },
    benchmarks: {
      antutu: 1650000,
      geekbench6Single: 2800,
      geekbench6Multi: 8500,
      wildLifeExtreme: "~4200",
    },
    stats: {
      views: "28.4K",
      favorites: "7.6K",
      shares: "1.9K",
      reviews: "876",
    },
  },
  {
    slug: "oneplus-13",
    name: "OnePlus 13",
    brand: "OnePlus",
    brandLogo: "OnePlus",
    year: 2026,
    rating: 4.6,
    reviewCount: 654,
    isFlagship: true,
    isEditorChoice: false,
    tags: ["5G", "Fast Charge", "Snapdragon 8 Gen 4", "120Hz"],
    image: "/images/s24ultra.jpg",
    specs: {
      display: "6.82 inches",
      displayType: "LTPO AMOLED 4.0",
      resolution: "3168 × 1440 px",
      pixelDensity: "510 ppi",
      screenToBodyRatio: "~89.9%",
      refreshRate: "144Hz Adaptive",
      brightness: "3000 nits peak",
      protection: "Gorilla Glass Victus 3",
      hdrSupport: "HDR10+, Dolby Vision",
      alwaysOnDisplay: "✅ Yes",
      chipset: "Snapdragon 8 Gen 4",
      cpu: "Octa-core (1×4.32GHz + 5×3.5GHz + 2×2.5GHz)",
      gpu: "Adreno 830",
      neuralEngine: "Hexagon NPU, 40 TOPS",
      ram: "16 GB",
      ramType: "LPDDR5X",
      storage: "256 GB / 512 GB / 1 TB",
      storageType: "UFS 4.1",
      camera: "50 MP",
      cameraWide: "50 MP, f/1.6, 23mm, 1/1.43\", 1.12µm, OIS",
      cameraUltraWide: "50 MP, f/2.0, 14mm, 114°",
      cameraTelephoto: "50 MP, f/2.6, 73mm, 3× optical zoom, OIS",
      cameraFeatures: "LED flash, Hasselblad Color Calibration, Night mode, Portrait, Pro mode, AI Photography",
      videoRecording: "8K@24/30fps, 4K@30/60/120fps, 1080p@30/60/120/240fps, HDR10+",
      frontCamera: "32 MP, f/2.2, 21mm, 1/3.14\"",
      frontFeatures: "4K video, HDR, Portrait, Night mode, AI Beauty",
      dimensions: "163.3 × 75.8 × 8.9 mm",
      weight: "222 g",
      build: "Aluminum frame · Gorilla Glass Victus 3 front/back",
      colors: ["Flowy Emerald", "Silky Black", "Velvet White", "Sapphire Blue"],
      colorFinish: "Matte glass back, polished aluminum frame",
      waterResistance: "IP68",
      battery: "6200 mAh",
      batteryType: "Li-Ion, non-removable",
      wiredCharging: "100W fast charge, 100% in 24 min",
      wirelessCharging: "50W wireless, 15W reverse wireless",
      batteryTechnology: "Adaptive charging, battery health monitoring, AI power management",
      videoPlayback: "Up to 32 hours",
      audioPlayback: "Up to 105 hours",
      standbyTime: "~580 hours",
      os: "Android 15, upgradable to Android 16",
      osUpdates: "4 years of OS updates, 5 years of security",
      audio: "Stereo speakers, Dolby Atmos, Spatial Audio, AI audio enhancement",
      headphoneJack: "No (USB-C)",
      audioRecording: "Stereo recording, noise cancellation",
      sim: "Nano-SIM + eSIM",
      networkBands: "5G NR (n1, n2, n3, n5, n7, n8, n12, n20, n25, n28, n38, n40, n41, n66, n71, n77, n78, n79), 4G LTE, 3G, 2G",
      wifi: "Wi-Fi 7 (802.11be) with 2×2 MIMO",
      bluetooth: "5.4, A2DP, LE, aptX HD, LDAC, aptX Lossless",
      nfc: "Yes (NFC, Google Pay)",
      usb: "USB-C 3.2 (up to 20Gbps)",
      gps: "GPS, GLONASS, GALILEO, BDS, QZSS, NavIC",
      ultraWideband: "UWB chip for spatial awareness",
      satelliteSOS: "Emergency SOS via satellite",
      crashDetection: "Yes",
      threadSupport: "Yes",
      security: "Under-display fingerprint, Face Unlock, AI Security",
      sensors: "Fingerprint, accelerometer, gyro, proximity, barometer, compass, ambient light sensor, color spectrum sensor",
      applePay: "No",
      magSafe: "No",
      emergencySOS: "Yes",
      boxContents: "OnePlus 13, 100W charger, USB-C cable, SIM tool, Case, Documentation",
      models: ["CPH2677 (Global)", "PJD110 (China)"],
      pricing: ["$999 · 256GB", "$1099 · 512GB", "$1299 · 1TB"],
    },
    benchmarks: {
      antutu: 2300000,
      geekbench6Single: 3150,
      geekbench6Multi: 9600,
      wildLifeExtreme: "~5100",
    },
    stats: {
      views: "22.6K",
      favorites: "5.8K",
      shares: "1.5K",
      reviews: "654",
    },
  },
  {
    slug: "xiaomi-15-pro",
    name: "Xiaomi 15 Pro",
    brand: "Xiaomi",
    brandLogo: "Xiaomi",
    year: 2026,
    rating: 4.5,
    reviewCount: 789,
    isFlagship: true,
    isEditorChoice: false,
    tags: ["5G", "Leica Camera", "Fast Charge", "Snapdragon 8 Gen 4"],
    image: "/images/s24ultra.jpg",
    specs: {
      display: "6.73 inches",
      displayType: "LTPO OLED 4.0",
      resolution: "3200 × 1440 px",
      pixelDensity: "522 ppi",
      screenToBodyRatio: "~90.3%",
      refreshRate: "144Hz Adaptive",
      brightness: "3500 nits peak",
      protection: "Xiaomi Shield Glass 2.0",
      hdrSupport: "HDR10+, Dolby Vision",
      alwaysOnDisplay: "✅ Yes",
      chipset: "Snapdragon 8 Gen 4",
      cpu: "Octa-core (1×4.32GHz + 5×3.5GHz + 2×2.5GHz)",
      gpu: "Adreno 830",
      neuralEngine: "Hexagon NPU, 40 TOPS",
      ram: "16 GB",
      ramType: "LPDDR5X",
      storage: "256 GB / 512 GB / 1 TB",
      storageType: "UFS 4.1",
      camera: "50 MP",
      cameraWide: "50 MP, f/1.4, 23mm, 1/1.33\", 1.2µm, OIS",
      cameraUltraWide: "50 MP, f/2.0, 14mm, 122°",
      cameraTelephoto: "50 MP, f/2.0, 78mm, 3.5× optical zoom, OIS",
      cameraFeatures: "Leica lenses, LED flash, Night mode, Portrait, Pro mode, Ultra RAW, AI Photography",
      videoRecording: "8K@24/30fps, 4K@30/60/120fps, 1080p@30/60/120/240fps, HDR10+, Dolby Vision",
      frontCamera: "32 MP, f/2.0, 21mm, 1/3.14\"",
      frontFeatures: "4K video, HDR, Portrait, Night mode, AI Beauty",
      dimensions: "161.4 × 75.3 × 8.3 mm",
      weight: "220 g",
      build: "Titanium frame · Glass front/back",
      colors: ["Black", "White", "Green", "Pink", "Gold"],
      colorFinish: "Matte glass back, polished titanium frame",
      waterResistance: "IP69",
      battery: "6000 mAh",
      batteryType: "Li-Ion, non-removable",
      wiredCharging: "120W fast charge, 100% in 18 min",
      wirelessCharging: "50W wireless, 15W reverse wireless",
      batteryTechnology: "Adaptive charging, battery health monitoring, AI power management",
      videoPlayback: "Up to 30 hours",
      audioPlayback: "Up to 100 hours",
      standbyTime: "~560 hours",
      os: "Android 15, upgradable to Android 16",
      osUpdates: "3 years of OS updates, 4 years of security",
      audio: "Stereo speakers, Dolby Atmos, Harman Kardon tuning, AI audio",
      headphoneJack: "No (USB-C)",
      audioRecording: "Stereo recording, noise cancellation, AI audio",
      sim: "Nano-SIM + eSIM",
      networkBands: "5G NR (n1, n2, n3, n5, n7, n8, n12, n20, n25, n28, n38, n40, n41, n66, n71, n77, n78, n79), 4G LTE, 3G, 2G",
      wifi: "Wi-Fi 7 (802.11be) with 2×2 MIMO",
      bluetooth: "5.4, A2DP, LE, aptX HD, LDAC, aptX Lossless",
      nfc: "Yes (NFC, Google Pay)",
      usb: "USB-C 3.2 (up to 20Gbps)",
      gps: "GPS, GLONASS, GALILEO, BDS, QZSS, NavIC",
      ultraWideband: "UWB chip for spatial awareness",
      satelliteSOS: "Emergency SOS via satellite",
      crashDetection: "Yes",
      threadSupport: "Yes",
      security: "Under-display fingerprint, Face Unlock, AI Security",
      sensors: "Fingerprint, accelerometer, gyro, proximity, barometer, compass, ambient light sensor, color spectrum sensor",
      applePay: "No",
      magSafe: "No",
      emergencySOS: "Yes",
      boxContents: "Xiaomi 15 Pro, 120W charger, USB-C cable, SIM tool, Case, Documentation",
      models: ["MZB0E5YEN (Global)", "MZB0E6YEN (China)"],
      pricing: ["$999 · 256GB", "$1099 · 512GB", "$1299 · 1TB"],
    },
    benchmarks: {
      antutu: 2350000,
      geekbench6Single: 3180,
      geekbench6Multi: 9700,
      wildLifeExtreme: "~5200",
    },
    stats: {
      views: "19.8K",
      favorites: "5.2K",
      shares: "1.3K",
      reviews: "789",
    },
  },
  {
    slug: "samsung-galaxy-z-fold-7",
    name: "Galaxy Z Fold 7",
    brand: "Samsung",
    brandLogo: "Samsung",
    year: 2026,
    rating: 4.7,
    reviewCount: 543,
    isFlagship: true,
    isEditorChoice: true,
    tags: ["Foldable", "5G", "S Pen", "Multitasking", "AI"],
    image: "/images/s24ultra.jpg",
    specs: {
      display: "7.8 inches",
      displayType: "Dynamic AMOLED 3X",
      resolution: "2224 × 1856 px",
      pixelDensity: "384 ppi",
      screenToBodyRatio: "~87.2%",
      refreshRate: "144Hz Adaptive",
      brightness: "2800 nits peak",
      protection: "UTG 2.0 (Ultra Thin Glass)",
      hdrSupport: "HDR10+",
      alwaysOnDisplay: "✅ Yes",
      chipset: "Snapdragon 8 Gen 4 for Galaxy",
      cpu: "Octa-core (1×4.32GHz + 5×3.5GHz + 2×2.5GHz)",
      gpu: "Adreno 830",
      neuralEngine: "Hexagon NPU, 45 TOPS",
      ram: "16 GB",
      ramType: "LPDDR5X",
      storage: "256 GB / 512 GB / 1 TB / 2 TB",
      storageType: "UFS 4.1",
      camera: "50 MP",
      cameraWide: "50 MP, f/1.8, 23mm, 1/1.56\", 1.0µm, OIS",
      cameraUltraWide: "12 MP, f/2.2, 13mm, 123°",
      cameraTelephoto: "10 MP, f/2.4, 70mm, 3× optical zoom, OIS",
      cameraFeatures: "LED flash, Night mode, Portrait, Pro mode, AI Photography",
      videoRecording: "8K@24/30fps, 4K@30/60/120fps, 1080p@30/60/120/240fps",
      frontCamera: "10 MP, f/2.0, 24mm, 1/3.2\"",
      frontFeatures: "4K video, HDR, Portrait mode, AI Beauty",
      dimensions: "153.5 × 68.1 × 13.4 mm",
      weight: "248 g",
      build: "Titanium frame · UTG 2.0 front/back",
      colors: ["Black", "White", "Gray", "Pink", "Blue"],
      colorFinish: "Matte titanium frame, matte glass back",
      waterResistance: "IP48",
      battery: "5200 mAh",
      batteryType: "Li-Ion, non-removable",
      wiredCharging: "45W fast charge, 50% in 25 min",
      wirelessCharging: "25W Qi, 15W reverse wireless",
      batteryTechnology: "Adaptive charging, battery health monitoring, AI power management",
      videoPlayback: "Up to 28 hours",
      audioPlayback: "Up to 92 hours",
      standbyTime: "~520 hours",
      os: "Android 15, upgradable to Android 16",
      osUpdates: "7 years of OS updates",
      audio: "Stereo speakers, Dolby Atmos, AKG tuning, 32-bit/384kHz",
      headphoneJack: "No (USB-C)",
      audioRecording: "Stereo recording, noise cancellation, AI audio",
      sim: "Nano-SIM + eSIM",
      networkBands: "5G NR (n1, n2, n3, n5, n7, n8, n12, n20, n25, n28, n38, n40, n41, n66, n71, n77, n78, n79), 4G LTE, 3G, 2G",
      wifi: "Wi-Fi 7 (802.11be) with 2×2 MIMO",
      bluetooth: "5.4, A2DP, LE, aptX HD, LDAC, aptX Lossless",
      nfc: "Yes (NFC, Samsung Pay)",
      usb: "USB-C 3.2 (up to 20Gbps)",
      gps: "GPS, GLONASS, GALILEO, BDS, QZSS, NavIC",
      ultraWideband: "UWB chip for spatial awareness",
      satelliteSOS: "Emergency SOS via satellite",
      crashDetection: "Yes",
      threadSupport: "Yes",
      security: "Side-mounted fingerprint, Face Unlock, Samsung Knox, AI Security",
      sensors: "Fingerprint, accelerometer, gyro, proximity, barometer, compass, ambient light sensor, hall sensor, SPO2",
      applePay: "No",
      magSafe: "No",
      emergencySOS: "Yes",
      boxContents: "Galaxy Z Fold 7, USB-C cable, SIM tool, Documentation, S Pen",
      models: ["SM-F958B (Global)", "SM-F958U (US)"],
      pricing: ["$1899 · 256GB", "$2099 · 512GB", "$2299 · 1TB", "$2499 · 2TB"],
    },
    benchmarks: {
      antutu: 2250000,
      geekbench6Single: 3100,
      geekbench6Multi: 9400,
      wildLifeExtreme: "~4800",
    },
    stats: {
      views: "16.8K",
      favorites: "4.2K",
      shares: "1.1K",
      reviews: "543",
    },
  },
  {
    slug: "apple-iphone-16",
    name: "iPhone 16",
    brand: "Apple",
    brandLogo: "Apple",
    year: 2026,
    rating: 4.6,
    reviewCount: 2345,
    isFlagship: false,
    isEditorChoice: false,
    tags: ["5G", "A18", "IP68", "AI"],
    image: "/images/s24ultra.jpg",
    specs: {
      display: "6.1 inches",
      displayType: "Super Retina XDR (OLED)",
      resolution: "2556 × 1179 px",
      pixelDensity: "460 ppi",
      screenToBodyRatio: "~86.2%",
      refreshRate: "60Hz",
      brightness: "1000 nits typ · 2000 nits peak",
      protection: "Ceramic Shield 2.0",
      hdrSupport: "HDR10, Dolby Vision",
      alwaysOnDisplay: "❌ No",
      chipset: "A18",
      cpu: "Hexa-core (2×3.78GHz + 4×2.11GHz)",
      gpu: "Apple GPU 5-core",
      neuralEngine: "16-core Neural Engine, 35 TOPS",
      ram: "6 GB",
      ramType: "LPDDR5X",
      storage: "128 GB / 256 GB / 512 GB",
      storageType: "NVMe",
      camera: "48 MP",
      cameraWide: "48 MP, f/1.6, 24mm, 1/1.28\", 1.22µm, OIS",
      cameraUltraWide: "12 MP, f/2.2, 13mm, 120°",
      cameraTelephoto: "12 MP, f/2.8, 52mm, 2× optical zoom, OIS",
      cameraFeatures: "LED flash, Photonic Engine, Deep Fusion, Smart HDR 6, Night mode, Portrait mode",
      videoRecording: "4K@24/25/30/60fps, 1080p@30/60/120/240fps, Dolby Vision HDR",
      frontCamera: "12 MP, f/1.9, 23mm, 1/3.6\", autofocus",
      frontFeatures: "Photonic Engine, Deep Fusion, Smart HDR 6, Night mode, Portrait mode, 4K HDR video",
      dimensions: "147.6 × 71.6 × 7.8 mm",
      weight: "170 g",
      build: "Aluminum frame · Ceramic Shield 2.0 front · glass back",
      colors: ["Black", "White", "Blue", "Green", "Pink", "Yellow"],
      colorFinish: "Anodized aluminum frame, glossy glass back",
      waterResistance: "IP68 (6m, 30 min)",
      battery: "3561 mAh",
      batteryType: "Li-Ion, non-removable",
      wiredCharging: "30W fast charge, 50% in ~25 min",
      wirelessCharging: "MagSafe 20W · Qi 12W",
      batteryTechnology: "Adaptive charging, optimized battery charging",
      videoPlayback: "Up to 22 hours",
      audioPlayback: "Up to 70 hours",
      standbyTime: "~480 hours",
      os: "iOS 18, upgradable to iOS 19",
      osUpdates: "6+ years of OS updates",
      audio: "Stereo speakers, Dolby Atmos, Spatial Audio",
      headphoneJack: "No (USB-C)",
      audioRecording: "Stereo recording",
      sim: "Nano-SIM + eSIM / Dual eSIM",
      networkBands: "5G NR (n1, n2, n3, n5, n7, n8, n12, n20, n25, n28, n30, n38, n40, n41, n48, n66, n70, n77, n78, n79), 4G LTE, 3G, 2G",
      wifi: "Wi-Fi 7 (802.11be) with 2×2 MIMO",
      bluetooth: "5.4, A2DP, LE, aptX HD",
      nfc: "Yes (NFC, Apple Pay)",
      usb: "USB-C 3.2 (up to 20Gbps)",
      gps: "GPS, GLONASS, GALILEO, BDS, QZSS, NavIC",
      ultraWideband: "UWB chip for spatial awareness",
      satelliteSOS: "Emergency SOS via satellite",
      crashDetection: "Yes",
      threadSupport: "Yes (Thread networking)",
      security: "Face ID, Secure Enclave",
      sensors: "Face ID, accelerometer, gyro, proximity, barometer, compass, ambient light sensor",
      applePay: "✅ Yes",
      magSafe: "Yes, with 20W charging",
      emergencySOS: "✅ Yes",
      boxContents: "iPhone 16, USB-C charge cable (1m), Documentation",
      models: ["A3083 (US)", "A3102 (Intl)"],
      pricing: ["$799 · 128GB", "$899 · 256GB", "$1099 · 512GB"],
    },
    benchmarks: {
      antutu: 1800000,
      geekbench6Single: 3300,
      geekbench6Multi: 8200,
      wildLifeExtreme: "~4100",
    },
    stats: {
      views: "32.5K",
      favorites: "8.4K",
      shares: "2.1K",
      reviews: "2345",
    },
  },
  {
    slug: "nothing-phone-3",
    name: "Phone (3)",
    brand: "Nothing",
    brandLogo: "Nothing",
    year: 2026,
    rating: 4.4,
    reviewCount: 432,
    isFlagship: true,
    isEditorChoice: false,
    tags: ["5G", "Glyph Interface", "Transparent", "AI"],
    image: "/images/s24ultra.jpg",
    specs: {
      display: "6.7 inches",
      displayType: "LTPO OLED",
      resolution: "2992 × 1344 px",
      pixelDensity: "489 ppi",
      screenToBodyRatio: "~87.6%",
      refreshRate: "144Hz Adaptive",
      brightness: "2800 nits peak",
      protection: "Gorilla Glass Victus 3",
      hdrSupport: "HDR10+",
      alwaysOnDisplay: "✅ Yes",
      chipset: "Snapdragon 8 Gen 4",
      cpu: "Octa-core (1×4.32GHz + 5×3.5GHz + 2×2.5GHz)",
      gpu: "Adreno 830",
      neuralEngine: "Hexagon NPU, 40 TOPS",
      ram: "12 GB",
      ramType: "LPDDR5X",
      storage: "256 GB / 512 GB",
      storageType: "UFS 4.1",
      camera: "50 MP",
      cameraWide: "50 MP, f/1.7, 23mm, 1/1.43\", OIS",
      cameraUltraWide: "50 MP, f/2.0, 14mm, 120°",
      cameraTelephoto: "50 MP, f/2.6, 70mm, 3× optical zoom, OIS",
      cameraFeatures: "LED flash, Night mode, Portrait, Pro mode, AI Photography",
      videoRecording: "8K@24fps, 4K@30/60fps, 1080p@30/60/120/240fps",
      frontCamera: "32 MP, f/2.0, 21mm, 1/3.14\"",
      frontFeatures: "4K video, HDR, Portrait, Night mode, AI Beauty",
      dimensions: "162.3 × 76.2 × 8.5 mm",
      weight: "215 g",
      build: "Aluminum frame · Glass front/back · Transparent design",
      colors: ["Black", "White", "Gray"],
      colorFinish: "Matte glass back, polished aluminum frame, Glyph interface",
      waterResistance: "IP68",
      battery: "5300 mAh",
      batteryType: "Li-Ion, non-removable",
      wiredCharging: "65W fast charge, 50% in 20 min",
      wirelessCharging: "45W wireless, 10W reverse wireless",
      batteryTechnology: "Adaptive charging, battery health monitoring, AI power management",
      videoPlayback: "Up to 28 hours",
      audioPlayback: "Up to 90 hours",
      standbyTime: "~540 hours",
      os: "Android 15, upgradable to Android 16",
      osUpdates: "4 years of OS updates, 5 years of security",
      audio: "Stereo speakers, Dolby Atmos, AI audio enhancement",
      headphoneJack: "No (USB-C)",
      audioRecording: "Stereo recording, noise cancellation, AI audio",
      sim: "Nano-SIM + eSIM",
      networkBands: "5G NR (n1, n2, n3, n5, n7, n8, n12, n20, n25, n28, n38, n40, n41, n66, n71, n77, n78, n79), 4G LTE, 3G, 2G",
      wifi: "Wi-Fi 7 (802.11be) with 2×2 MIMO",
      bluetooth: "5.4, A2DP, LE, aptX HD, LDAC",
      nfc: "Yes (NFC, Google Pay)",
      usb: "USB-C 3.2 (up to 20Gbps)",
      gps: "GPS, GLONASS, GALILEO, BDS, QZSS, NavIC",
      ultraWideband: "UWB chip for spatial awareness",
      satelliteSOS: "Emergency SOS via satellite",
      crashDetection: "Yes",
      threadSupport: "Yes",
      security: "Under-display fingerprint, Face Unlock, Glyph lighting",
      sensors: "Fingerprint, accelerometer, gyro, proximity, barometer, compass, ambient light sensor, color spectrum sensor",
      applePay: "No",
      magSafe: "No",
      emergencySOS: "Yes",
      boxContents: "Nothing Phone (3), USB-C cable, SIM tool, Documentation",
      models: ["A073 (Global)", "A073U (US)"],
      pricing: ["$849 · 256GB", "$949 · 512GB"],
    },
    benchmarks: {
      antutu: 2150000,
      geekbench6Single: 3050,
      geekbench6Multi: 9200,
      wildLifeExtreme: "~4600",
    },
    stats: {
      views: "14.2K",
      favorites: "3.8K",
      shares: "987",
      reviews: "432",
    },
  },
  {
    slug: "sony-xperia-1-vii",
    name: "Xperia 1 VII",
    brand: "Sony",
    brandLogo: "Sony",
    year: 2026,
    rating: 4.5,
    reviewCount: 321,
    isFlagship: true,
    isEditorChoice: false,
    tags: ["5G", "Cinema", "Camera", "4K", "Pro"],
    image: "/images/s24ultra.jpg",
    specs: {
      display: "6.5 inches",
      displayType: "OLED 4K HDR",
      resolution: "3840 × 1644 px",
      pixelDensity: "643 ppi",
      screenToBodyRatio: "~84.2%",
      refreshRate: "144Hz Adaptive",
      brightness: "1500 nits peak",
      protection: "Gorilla Glass Victus 3",
      hdrSupport: "HDR10, HDR10+, Dolby Vision",
      alwaysOnDisplay: "✅ Yes",
      chipset: "Snapdragon 8 Gen 4",
      cpu: "Octa-core (1×4.32GHz + 5×3.5GHz + 2×2.5GHz)",
      gpu: "Adreno 830",
      neuralEngine: "Hexagon NPU, 40 TOPS",
      ram: "16 GB",
      ramType: "LPDDR5X",
      storage: "256 GB / 512 GB / 1 TB",
      storageType: "UFS 4.1",
      camera: "48 MP",
      cameraWide: "48 MP, f/1.8, 24mm, 1/1.33\", OIS",
      cameraUltraWide: "12 MP, f/2.2, 14mm, 120°",
      cameraTelephoto: "12 MP, f/2.6, 85mm, 3.5× optical zoom, OIS",
      cameraFeatures: "ZEISS lenses, LED flash, Night mode, Portrait, Pro mode, Cinema Pro, Photography Pro",
      videoRecording: "8K@24fps, 4K@30/60/120fps, 1080p@30/60/120/240fps, HDR10, Dolby Vision",
      frontCamera: "12 MP, f/2.0, 24mm, 1/3.2\"",
      frontFeatures: "4K video, HDR, Portrait mode, Pro features",
      dimensions: "165.0 × 71.0 × 8.2 mm",
      weight: "190 g",
      build: "Aluminum frame · Gorilla Glass Victus 3 front/back",
      colors: ["Black", "White", "Green", "Red"],
      colorFinish: "Matte glass back, polished aluminum frame",
      waterResistance: "IP68 (1.5m, 30 min)",
      battery: "5800 mAh",
      batteryType: "Li-Ion, non-removable",
      wiredCharging: "45W fast charge, 50% in 25 min",
      wirelessCharging: "25W Qi, 10W reverse wireless",
      batteryTechnology: "Adaptive charging, battery health monitoring, AI power management",
      videoPlayback: "Up to 25 hours",
      audioPlayback: "Up to 85 hours",
      standbyTime: "~500 hours",
      os: "Android 15, upgradable to Android 16",
      osUpdates: "3 years of OS updates, 4 years of security",
      audio: "Stereo speakers, Dolby Atmos, 360 Reality Audio, DSEE Ultimate",
      headphoneJack: "Yes (3.5mm)",
      audioRecording: "Stereo recording, noise cancellation, professional mics",
      sim: "Nano-SIM + eSIM",
      networkBands: "5G NR (n1, n2, n3, n5, n7, n8, n12, n20, n25, n28, n38, n40, n41, n66, n71, n77, n78, n79), 4G LTE, 3G, 2G",
      wifi: "Wi-Fi 7 (802.11be) with 2×2 MIMO",
      bluetooth: "5.4, A2DP, LE, aptX HD, LDAC, aptX Lossless",
      nfc: "Yes (NFC, Google Pay)",
      usb: "USB-C 3.2 (up to 20Gbps)",
      gps: "GPS, GLONASS, GALILEO, BDS, QZSS, NavIC",
      ultraWideband: "UWB chip for spatial awareness",
      satelliteSOS: "Emergency SOS via satellite",
      crashDetection: "Yes",
      threadSupport: "Yes",
      security: "Fingerprint (side-mounted), Face Unlock, AI Security",
      sensors: "Fingerprint, accelerometer, gyro, proximity, barometer, compass, ambient light sensor, color spectrum sensor",
      applePay: "No",
      magSafe: "No",
      emergencySOS: "Yes",
      boxContents: "Xperia 1 VII, USB-C cable, Documentation",
      models: ["XQ-DQ72 (Global)", "XQ-DQ72U (US)"],
      pricing: ["$1199 · 256GB", "$1399 · 512GB", "$1599 · 1TB"],
    },
    benchmarks: {
      antutu: 2100000,
      geekbench6Single: 3000,
      geekbench6Multi: 9000,
      wildLifeExtreme: "~4500",
    },
    stats: {
      views: "11.8K",
      favorites: "2.7K",
      shares: "654",
      reviews: "321",
    },
  },
  {
    slug: "motorola-edge-60-ultra",
    name: "Edge 60 Ultra",
    brand: "Motorola",
    brandLogo: "Motorola",
    year: 2026,
    rating: 4.3,
    reviewCount: 456,
    isFlagship: true,
    isEditorChoice: false,
    tags: ["5G", "AI", "Camera", "Fast Charge"],
    image: "/images/s24ultra.jpg",
    specs: {
      display: "6.9 inches",
      displayType: "LTPO OLED",
      resolution: "3168 × 1440 px",
      pixelDensity: "510 ppi",
      screenToBodyRatio: "~89.2%",
      refreshRate: "144Hz Adaptive",
      brightness: "2800 nits peak",
      protection: "Gorilla Glass Victus 3",
      hdrSupport: "HDR10+, Dolby Vision",
      alwaysOnDisplay: "✅ Yes",
      chipset: "Snapdragon 8 Gen 4",
      cpu: "Octa-core (1×4.32GHz + 5×3.5GHz + 2×2.5GHz)",
      gpu: "Adreno 830",
      neuralEngine: "Hexagon NPU, 40 TOPS",
      ram: "16 GB",
      ramType: "LPDDR5X",
      storage: "256 GB / 512 GB / 1 TB",
      storageType: "UFS 4.1",
      camera: "200 MP",
      cameraWide: "200 MP, f/1.6, 23mm, 1/1.4\", OIS",
      cameraUltraWide: "50 MP, f/2.0, 14mm, 120°",
      cameraTelephoto: "50 MP, f/2.8, 120mm, 4× optical zoom, OIS",
      cameraFeatures: "LED flash, Night mode, Portrait, Pro mode, AI Photography",
      videoRecording: "8K@24/30fps, 4K@30/60/120fps, 1080p@30/60/120/240fps, HDR10+",
      frontCamera: "32 MP, f/2.0, 21mm, 1/3.14\"",
      frontFeatures: "4K video, HDR, Portrait, Night mode, AI Beauty",
      dimensions: "161.8 × 74.2 × 8.3 mm",
      weight: "210 g",
      build: "Aluminum frame · Glass front/back",
      colors: ["Black", "White", "Blue", "Green", "Purple"],
      colorFinish: "Matte glass back, polished aluminum frame",
      waterResistance: "IP69",
      battery: "6500 mAh",
      batteryType: "Li-Ion, non-removable",
      wiredCharging: "125W fast charge, 100% in 20 min",
      wirelessCharging: "50W wireless, 15W reverse wireless",
      batteryTechnology: "Adaptive charging, battery health monitoring, AI power management",
      videoPlayback: "Up to 35 hours",
      audioPlayback: "Up to 110 hours",
      standbyTime: "~620 hours",
      os: "Android 15, upgradable to Android 16",
      osUpdates: "4 years of OS updates, 5 years of security",
      audio: "Stereo speakers, Dolby Atmos, Spatial Audio",
      headphoneJack: "No (USB-C)",
      audioRecording: "Stereo recording, noise cancellation, AI audio",
      sim: "Nano-SIM + eSIM",
      networkBands: "5G NR (n1, n2, n3, n5, n7, n8, n12, n20, n25, n28, n38, n40, n41, n66, n71, n77, n78, n79), 4G LTE, 3G, 2G",
      wifi: "Wi-Fi 7 (802.11be) with 2×2 MIMO",
      bluetooth: "5.4, A2DP, LE, aptX HD, LDAC, aptX Lossless",
      nfc: "Yes (NFC, Google Pay)",
      usb: "USB-C 3.2 (up to 20Gbps)",
      gps: "GPS, GLONASS, GALILEO, BDS, QZSS, NavIC",
      ultraWideband: "UWB chip for spatial awareness",
      satelliteSOS: "Emergency SOS via satellite",
      crashDetection: "Yes",
      threadSupport: "Yes",
      security: "Under-display fingerprint, Face Unlock, AI Security",
      sensors: "Fingerprint, accelerometer, gyro, proximity, barometer, compass, ambient light sensor, color spectrum sensor",
      applePay: "No",
      magSafe: "No",
      emergencySOS: "Yes",
      boxContents: "Motorola Edge 60 Ultra, 125W charger, USB-C cable, SIM tool, Case, Documentation",
      models: ["XT2315 (Global)", "XT2315U (US)"],
      pricing: ["$899 · 256GB", "$999 · 512GB", "$1199 · 1TB"],
    },
    benchmarks: {
      antutu: 2400000,
      geekbench6Single: 3250,
      geekbench6Multi: 9800,
      wildLifeExtreme: "~5300",
    },
    stats: {
      views: "13.6K",
      favorites: "3.2K",
      shares: "789",
      reviews: "456",
    },
  },
  {
    slug: "asus-rog-phone-9-pro",
    name: "ROG Phone 9 Pro",
    brand: "Asus",
    brandLogo: "Asus",
    year: 2026,
    rating: 4.8,
    reviewCount: 234,
    isFlagship: true,
    isEditorChoice: true,
    tags: ["Gaming", "5G", "AI", "Cooling", "RGB"],
    image: "/images/s24ultra.jpg",
    specs: {
      display: "6.78 inches",
      displayType: "AMOLED 5K",
      resolution: "3168 × 1440 px",
      pixelDensity: "512 ppi",
      screenToBodyRatio: "~84.8%",
      refreshRate: "165Hz Adaptive",
      brightness: "2600 nits peak",
      protection: "Gorilla Glass Victus 3",
      hdrSupport: "HDR10+, Dolby Vision",
      alwaysOnDisplay: "✅ Yes",
      chipset: "Snapdragon 8 Gen 4 (overclocked)",
      cpu: "Octa-core (1×4.5GHz + 5×3.8GHz + 2×2.8GHz)",
      gpu: "Adreno 830 (overclocked)",
      neuralEngine: "Hexagon NPU, 50 TOPS",
      ram: "18 GB",
      ramType: "LPDDR5X",
      storage: "512 GB / 1 TB / 2 TB",
      storageType: "UFS 4.1",
      camera: "50 MP",
      cameraWide: "50 MP, f/1.8, 23mm, 1/1.43\", OIS",
      cameraUltraWide: "13 MP, f/2.2, 13mm, 120°",
      cameraTelephoto: "8 MP, f/2.4, 80mm, 3× optical zoom, OIS",
      cameraFeatures: "LED flash, Night mode, Portrait, Pro mode, AI Photography",
      videoRecording: "8K@24fps, 4K@30/60/120fps, 1080p@30/60/120/240fps, HDR10+",
      frontCamera: "32 MP, f/2.0, 21mm, 1/3.14\"",
      frontFeatures: "4K video, HDR, Portrait, Night mode, AI Beauty",
      dimensions: "173.0 × 77.0 × 10.3 mm",
      weight: "260 g",
      build: "Aluminum frame · Gorilla Glass front/back · RGB lighting",
      colors: ["Black", "White", "Blue"],
      colorFinish: "Matte glass back, polished aluminum frame, RGB panel",
      waterResistance: "IP68",
      battery: "7000 mAh",
      batteryType: "Li-Ion, non-removable",
      wiredCharging: "65W fast charge, 50% in 20 min",
      wirelessCharging: "15W Qi",
      batteryTechnology: "Adaptive charging, battery health monitoring, AI power management, gaming mode",
      videoPlayback: "Up to 38 hours",
      audioPlayback: "Up to 125 hours",
      standbyTime: "~680 hours",
      os: "Android 15, upgradable to Android 16",
      osUpdates: "3 years of OS updates, 4 years of security",
      audio: "Stereo speakers, Dolby Atmos, Dirac tuning, AI audio, GameFX",
      headphoneJack: "Yes (3.5mm)",
      audioRecording: "Stereo recording, noise cancellation, AI audio, GameVoice",
      sim: "Nano-SIM + eSIM",
      networkBands: "5G NR (n1, n2, n3, n5, n7, n8, n12, n20, n25, n28, n38, n40, n41, n66, n71, n77, n78, n79), 4G LTE, 3G, 2G",
      wifi: "Wi-Fi 7 (802.11be) with 2×2 MIMO",
      bluetooth: "5.4, A2DP, LE, aptX HD, LDAC, aptX Lossless",
      nfc: "Yes (NFC, Google Pay)",
      usb: "USB-C 3.2 (up to 20Gbps)",
      gps: "GPS, GLONASS, GALILEO, BDS, QZSS, NavIC",
      ultraWideband: "UWB chip for spatial awareness",
      satelliteSOS: "Emergency SOS via satellite",
      crashDetection: "Yes",
      threadSupport: "Yes",
      security: "Under-display fingerprint, Face Unlock, AI Security, GameGuard",
      sensors: "Fingerprint, accelerometer, gyro, proximity, barometer, compass, ambient light sensor, color spectrum sensor, game trigger",
      applePay: "No",
      magSafe: "No",
      emergencySOS: "Yes",
      boxContents: "ROG Phone 9 Pro, 65W charger, USB-C cable, SIM tool, AeroActive Cooler X, Case, Documentation",
      models: ["ZS678 (Global)", "ZS678U (US)"],
      pricing: ["$1299 · 512GB", "$1499 · 1TB", "$1699 · 2TB"],
    },
    benchmarks: {
      antutu: 2800000,
      geekbench6Single: 3500,
      geekbench6Multi: 10500,
      wildLifeExtreme: "~5800",
    },
    stats: {
      views: "17.8K",
      favorites: "4.5K",
      shares: "1.2K",
      reviews: "234",
    },
  },
  {
    slug: "google-pixel-9",
    name: "Pixel 9",
    brand: "Google",
    brandLogo: "Google",
    year: 2026,
    rating: 4.5,
    reviewCount: 1234,
    isFlagship: false,
    isEditorChoice: false,
    tags: ["5G", "AI", "Camera", "Stock Android"],
    image: "/images/s24ultra.jpg",
    specs: {
      display: "6.3 inches",
      displayType: "LTPO OLED",
      resolution: "2400 × 1080 px",
      pixelDensity: "419 ppi",
      screenToBodyRatio: "~86.4%",
      refreshRate: "120Hz Adaptive",
      brightness: "2000 nits peak",
      protection: "Gorilla Glass Victus 3",
      hdrSupport: "HDR10+",
      alwaysOnDisplay: "✅ Yes",
      chipset: "Google Tensor G4",
      cpu: "Nona-core (1×3.2GHz + 4×2.6GHz + 4×2.2GHz)",
      gpu: "Immortalis-G720 MC10",
      neuralEngine: "TPU 4.0, Titan M3, 40 TOPS",
      ram: "8 GB",
      ramType: "LPDDR5X",
      storage: "128 GB / 256 GB",
      storageType: "UFS 4.0",
      camera: "50 MP",
      cameraWide: "50 MP, f/1.7, 25mm, 1/1.31\", OIS",
      cameraUltraWide: "12 MP, f/2.2, 13mm, 120°",
      cameraTelephoto: "12 MP, f/2.6, 50mm, 2× optical zoom, OIS",
      cameraFeatures: "LED flash, Super Res Zoom, Magic Eraser, Photo Unblur, Night Sight, Real Tone",
      videoRecording: "4K@30/60fps, 1080p@30/60/120fps, 10-bit HDR",
      frontCamera: "10.5 MP, f/2.0, 20mm, 1/3.1\"",
      frontFeatures: "4K video, HDR, Portrait mode, Face Unlock, AI Beauty",
      dimensions: "155.6 × 73.2 × 8.5 mm",
      weight: "198 g",
      build: "Aluminum frame · Gorilla Glass Victus 3 front/back",
      colors: ["Obsidian", "Porcelain", "Bay", "Rose"],
      colorFinish: "Satin aluminum frame, matte glass back",
      waterResistance: "IP68 (1.5m, 30 min)",
      battery: "4700 mAh",
      batteryType: "Li-Ion, non-removable",
      wiredCharging: "27W fast charge, 50% in 30 min",
      wirelessCharging: "18W Qi, 12W reverse wireless",
      batteryTechnology: "Adaptive charging, battery health monitoring, AI power management",
      videoPlayback: "Up to 22 hours",
      audioPlayback: "Up to 75 hours",
      standbyTime: "~450 hours",
      os: "Android 15, upgradable to Android 16",
      osUpdates: "7 years of OS updates, Feature Drops",
      audio: "Stereo speakers, Spatial Audio, noise cancellation",
      headphoneJack: "No (USB-C)",
      audioRecording: "Stereo recording, Audio Magic Eraser",
      sim: "Nano-SIM + eSIM",
      networkBands: "5G NR (n1, n2, n3, n5, n7, n8, n12, n20, n25, n28, n38, n40, n41, n66, n71, n77, n78), 4G LTE, 3G, 2G",
      wifi: "Wi-Fi 7 (802.11be) with 2×2 MIMO",
      bluetooth: "5.4, A2DP, LE, aptX HD",
      nfc: "Yes (NFC, Google Pay)",
      usb: "USB-C 3.2",
      gps: "GPS, GLONASS, GALILEO, BDS, QZSS",
      ultraWideband: "UWB chip for spatial awareness",
      satelliteSOS: "Emergency SOS via satellite",
      crashDetection: "Yes",
      threadSupport: "Yes",
      security: "Face Unlock, Fingerprint, Titan M3 chip, VPN by Google",
      sensors: "Face unlock, fingerprint, accelerometer, gyro, proximity, barometer, compass, ambient light sensor",
      applePay: "No",
      magSafe: "No",
      emergencySOS: "Yes",
      boxContents: "Pixel 9, USB-C cable, Quick Switch Adapter, Documentation",
      models: ["G1MNW (Global)", "G9BQD (US)"],
      pricing: ["$799 · 128GB", "$899 · 256GB"],
    },
    benchmarks: {
      antutu: 1450000,
      geekbench6Single: 2600,
      geekbench6Multi: 7800,
      wildLifeExtreme: "~3800",
    },
    stats: {
      views: "25.6K",
      favorites: "6.8K",
      shares: "1.7K",
      reviews: "1234",
    },
  },
];

// Helper Functions
export function getPhoneBySlug(slug: string): Phone | undefined {
  return phonesData.find(phone => phone.slug === slug);
}

export function getRelatedPhones(currentSlug: string, limit: number = 10): Phone[] {
  return phonesData
    .filter(phone => phone.slug !== currentSlug)
    .slice(0, limit);
}

export function getAllBrands(): string[] {
  const brands = new Set(phonesData.map(phone => phone.brand));
  return Array.from(brands);
}

export function getPhonesByBrand(brand: string): Phone[] {
  return phonesData.filter(phone => 
    phone.brand.toLowerCase() === brand.toLowerCase()
  );
}

export function getLatestPhones(limit: number = 6): Phone[] {
  return [...phonesData]
    .sort((a, b) => b.year - a.year)
    .slice(0, limit);
}

export function getTopRatedPhones(limit: number = 5): Phone[] {
  return [...phonesData]
    .sort((a, b) => b.rating - a.rating)
    .slice(0, limit);
}

export function getFlagshipPhones(): Phone[] {
  return phonesData.filter(phone => phone.isFlagship);
}

export function getEditorChoicePhones(): Phone[] {
  return phonesData.filter(phone => phone.isEditorChoice);
}